services:
  - type: web
    name: remoce-server
    env: docker
    rootDir: server
    autoDeploy: true
    envVars:
      - key: CORS_ORIGIN
        value: ""
      - key: SERP_API_KEY
        value: ""
      - key: MOJEEK_API_KEY
        value: ""
      - key: SCRAPINGBEE_KEY
        value: ""
      - key: SCRAPINGANT_KEYS
        value: ""
